name: qavision
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.8
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  hotkey_manager: ^0.2.3
  image: ^4.8.0
  intl: 0.20.2
  pasteboard: ^0.1.0+2
  path: ^1.9.1
  path_provider: ^2.1.5
  screen_capturer: ^0.2.3
  share_plus: ^10.1.4
  storybook_flutter: ^0.14.1
  uuid: ^4.5.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
